import React, { useState, useEffect } from 'react';
import QRCode from 'qrcode';
import { Order, SystemSettings } from '../../types';
import cardsCraftedLogo from '../../assets/images/cards_crafted_logo_1786446210358.jpg';
import { useGoogleDrive } from '../../context/GoogleDriveContext';
import { GoogleDriveHubModal } from '../drive/GoogleDriveHubModal';
import { generateOrderSummaryPdf } from '../../utils/pdfInvoiceGenerator';
import {
  Printer,
  FileDown,
  X,
  Sparkles,
  Receipt,
  FileText,
  CheckCircle2,
  QrCode,
  Maximize2,
  ExternalLink,
  Cloud,
  Check
} from 'lucide-react';
import { BillQRCodeModal } from './BillQRCodeModal';

interface InvoiceModalProps {
  isOpen: boolean;
  onClose: () => void;
  order: Order | null;
  settings: SystemSettings | null;
  initialMode?: 'RECEIPT' | 'INVOICE';
}

export const InvoiceModal: React.FC<InvoiceModalProps> = ({
  isOpen,
  onClose,
  order,
  settings,
  initialMode = 'RECEIPT'
}) => {
  const [docType, setDocType] = useState<'RECEIPT' | 'INVOICE'>(initialMode);
  const [showQRModal, setShowQRModal] = useState(false);
  const [showDriveModal, setShowDriveModal] = useState(false);
  const [qrCodeDataUrl, setQrCodeDataUrl] = useState<string>('');
  const [savingToDrive, setSavingToDrive] = useState(false);
  const [driveSavedLink, setDriveSavedLink] = useState<string | null>(null);

  const { isConnected: isDriveConnected, uploadFile, connectDrive } = useGoogleDrive();

  const bizName = settings?.businessName || 'Cards Crafted';
  const bizAddr = settings?.address || '102 Creative Craft Lane, Handloom Market';
  const bizCityState = `${settings?.city || 'Mumbai'}, ${settings?.state || 'Maharashtra'} - ${settings?.pincode || '400012'}`;
  const bizPhone = settings?.phone || '+91 98201 12345';
  const bizEmail = settings?.email || 'contact@cardscrafted.com';
  const gstin = settings?.gstin || '27AABCC1234D1ZP';
  const upiId = settings?.upiId || 'shiv.khante5-2@okaxis';

  const isPaidInFull = order ? order.balanceAmount <= 0 : false;
  const isPartiallyPaid = order ? order.paidAmount > 0 && order.balanceAmount > 0 : false;
  const billAmountToPay = order ? (order.balanceAmount > 0 ? order.balanceAmount : order.grandTotal) : 0;

  useEffect(() => {
    if (order && upiId) {
      const upiUri = `upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(
        bizName
      )}&am=${order.grandTotal.toFixed(2)}&cu=INR&tn=${encodeURIComponent(
        `Order #${order.orderNumber}`
      )}`;

      QRCode.toDataURL(upiUri, {
        width: 140,
        margin: 1,
        color: {
          dark: '#0f172a',
          light: '#ffffff'
        }
      })
        .then(url => setQrCodeDataUrl(url))
        .catch(err => console.error('Error generating inline QR:', err));
    }
  }, [order, upiId, bizName]);

  if (!isOpen || !order) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleSaveToDrive = async () => {
    if (!isDriveConnected) {
      setShowDriveModal(true);
      return;
    }

    if (!order) return;
    setSavingToDrive(true);
    try {
      // Create printable HTML snapshot of the invoice
      const invoiceElement = document.getElementById('printable-receipt');
      const invoiceHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Invoice #${order.orderNumber} - ${bizName}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 24px; color: #1e293b; max-width: 800px; margin: 0 auto; line-height: 1.5; }
    h1 { margin: 0 0 4px; font-size: 20px; font-weight: 800; color: #0f172a; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: #f8fafc; border-bottom: 2px solid #cbd5e1; text-align: left; padding: 8px; font-size: 12px; }
    td { border-bottom: 1px solid #e2e8f0; padding: 8px; font-size: 12px; }
    .total-row { font-weight: bold; background: #f1f5f9; }
    .badge { display: inline-block; padding: 3px 8px; border-radius: 9999px; font-size: 11px; font-weight: bold; }
    .header-box { border-bottom: 2px solid #0f172a; padding-bottom: 16px; margin-bottom: 16px; }
  </style>
</head>
<body>
  ${invoiceElement ? invoiceElement.innerHTML : `<h1>${bizName} - Order #${order.orderNumber}</h1><p>Customer: ${order.customerName}</p><p>Total: ₹${order.grandTotal.toFixed(2)}</p>`}
  <footer style="margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 10px; font-size: 10px; color: #64748b; text-align: center;">
    Generated by Cards Crafted Studio • Saved to Google Drive Cloud Storage
  </footer>
</body>
</html>`;

      const blob = new Blob([invoiceHtml], { type: 'text/html;charset=utf-8' });
      const file = new File([blob], `${docType === 'RECEIPT' ? 'Receipt' : 'Invoice'}_${order.orderNumber}_${order.customerName.replace(/[^a-zA-Z0-9]/g, '_')}.html`, { type: 'text/html' });

      const uploaded = await uploadFile(file, `Invoice document for Order #${order.orderNumber}`);
      if (uploaded.webViewLink) {
        setDriveSavedLink(uploaded.webViewLink);
      }
      setTimeout(() => setDriveSavedLink(null), 5000);
    } catch (err) {
      console.error('Failed to save invoice to Google Drive:', err);
    } finally {
      setSavingToDrive(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 bg-slate-950/70 backdrop-blur-xs overflow-y-auto print:p-0 print:bg-white print:static print:overflow-visible print:z-auto print:block">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-3xl overflow-hidden my-4 max-h-[92vh] flex flex-col print:m-0 print:p-0 print:border-none print:shadow-none print:max-h-none print:w-full print:rounded-none">
        
        {/* Modal Action Bar (Hidden on Print) */}
        <div className="px-5 py-3.5 bg-slate-900 text-white flex flex-wrap items-center justify-between gap-3 print:hidden shrink-0">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-purple-600/30 flex items-center justify-center text-purple-400 border border-purple-500/30">
              {docType === 'RECEIPT' ? <Receipt className="w-4 h-4 text-purple-300" /> : <FileText className="w-4 h-4 text-blue-300" />}
            </div>
            <div>
              <h3 className="font-black text-sm text-white flex items-center gap-2">
                {docType === 'RECEIPT' ? 'Customer Receipt' : 'Tax Invoice'} - #{order.orderNumber}
              </h3>
              <p className="text-[10px] text-slate-400">Printer-friendly formatted document</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* Click to Display Bill QR */}
            <button
              type="button"
              onClick={() => setShowQRModal(true)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold rounded-xl shadow-xs transition-colors cursor-pointer"
              title="Click to display QR of total amount bill"
            >
              <QrCode className="w-4 h-4 text-purple-200" />
              <span>Display Bill QR</span>
            </button>

            {/* Toggle Receipt vs Invoice */}
            <div className="bg-slate-800 p-0.5 rounded-lg flex items-center text-xs font-bold border border-slate-700">
              <button
                type="button"
                onClick={() => setDocType('RECEIPT')}
                className={`px-2.5 py-1 rounded-md transition-all cursor-pointer ${
                  docType === 'RECEIPT' ? 'bg-purple-600 text-white shadow-xs' : 'text-slate-400 hover:text-white'
                }`}
              >
                Receipt
              </button>
              <button
                type="button"
                onClick={() => setDocType('INVOICE')}
                className={`px-2.5 py-1 rounded-md transition-all cursor-pointer ${
                  docType === 'INVOICE' ? 'bg-blue-600 text-white shadow-xs' : 'text-slate-400 hover:text-white'
                }`}
              >
                Tax Invoice
              </button>
            </div>

            {/* Save to Google Drive Button */}
            <button
              type="button"
              onClick={handleSaveToDrive}
              disabled={savingToDrive}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all shadow-xs cursor-pointer ${
                driveSavedLink
                  ? 'bg-emerald-600 text-white'
                  : 'bg-blue-600 hover:bg-blue-500 text-white'
              }`}
              title="Save formatted invoice directly to your Google Drive Cloud storage"
            >
              {driveSavedLink ? (
                <>
                  <Check className="w-3.5 h-3.5" />
                  <span>Saved to Drive!</span>
                </>
              ) : (
                <>
                  <Cloud className={`w-3.5 h-3.5 ${savingToDrive ? 'animate-pulse' : ''}`} />
                  <span>{savingToDrive ? 'Uploading...' : 'Save to Drive'}</span>
                </>
              )}
            </button>

            <button
              type="button"
              onClick={() =>
                generateOrderSummaryPdf(order, settings, {
                  docTitle: docType === 'RECEIPT' ? 'CUSTOMER RECEIPT' : 'TAX INVOICE'
                })
              }
              className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold rounded-xl shadow-xs transition-colors cursor-pointer"
              title="Export professional invoice summary as PDF (.pdf)"
            >
              <FileDown className="w-3.5 h-3.5" />
              <span>Export as PDF</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3.5 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl shadow-xs transition-colors cursor-pointer"
            >
              <Printer className="w-4 h-4" />
              <span>Print</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-white hover:bg-slate-800 rounded-lg transition-colors cursor-pointer"
              title="Close Preview"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Area */}
        <div className="p-6 sm:p-8 overflow-y-auto flex-1 print:p-0 print:overflow-visible text-slate-800 text-xs sm:text-sm bg-white" id="printable-receipt">
          
          {/* Header & Studio Details */}
          <div className="flex flex-col sm:flex-row justify-between items-start border-b-2 border-slate-900 pb-5 mb-5 gap-4">
            <div className="space-y-1">
              <div className="flex items-center gap-3 mb-2">
                <img
                  src={settings?.logoUrl || cardsCraftedLogo}
                  alt={bizName}
                  className="h-12 sm:h-14 w-12 sm:w-14 object-contain rounded-full shrink-0"
                  referrerPolicy="no-referrer"
                />
                <div>
                  <h1 className="font-black text-lg sm:text-xl text-slate-900 tracking-tight">{bizName}</h1>
                  <p className="text-[11px] font-semibold text-purple-700 uppercase tracking-widest">Handcrafted Art & Custom Printing</p>
                </div>
              </div>
              <p className="text-xs text-slate-600 leading-tight">{bizAddr}</p>
              <p className="text-xs text-slate-600">{bizCityState}</p>
              <p className="text-xs text-slate-600">Tel: <strong className="text-slate-800">{bizPhone}</strong> • Email: <strong className="text-slate-800">{bizEmail}</strong></p>
              {gstin && <p className="text-xs font-mono font-bold text-slate-700">GSTIN: {gstin}</p>}
            </div>

            <div className="text-left sm:text-right w-full sm:w-auto shrink-0 bg-slate-50 sm:bg-transparent p-3 sm:p-0 rounded-xl border sm:border-0 border-slate-200">
              <span className={`inline-block px-3 py-1 text-xs font-black tracking-wider uppercase rounded-md mb-1.5 ${
                docType === 'RECEIPT' ? 'bg-purple-100 text-purple-900 border border-purple-200' : 'bg-blue-100 text-blue-900 border border-blue-200'
              }`}>
                {docType === 'RECEIPT' ? 'CUSTOMER RECEIPT' : 'TAX INVOICE'}
              </span>
              <p className="text-base font-black text-slate-900">
                {docType === 'RECEIPT' ? `REC-${order.orderNumber}` : `INV-${order.orderNumber}`}
              </p>
              <p className="text-xs text-slate-600 mt-0.5">Order Date: <strong className="text-slate-900">{new Date(order.orderDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</strong></p>
              <p className="text-xs text-slate-600">Target Delivery: <strong className="text-slate-900">{new Date(order.expectedDeliveryDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</strong></p>
              <p className="text-xs text-slate-600">Priority: <strong className="text-purple-700">{order.priority || 'STANDARD'}</strong></p>
            </div>
          </div>

          {/* Customer & Settlement Status Details */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-4 bg-slate-50 rounded-xl mb-5 border border-slate-200">
            <div>
              <h4 className="text-[11px] font-black uppercase text-slate-400 tracking-wider mb-1.5">Customer Bill-To</h4>
              <p className="font-black text-slate-900 text-sm sm:text-base">{order.customerName}</p>
              <p className="text-xs text-slate-700 mt-0.5">Phone: <span className="font-semibold">{order.customerPhone}</span></p>
              {order.customerEmail && <p className="text-xs text-slate-700">Email: {order.customerEmail}</p>}
              {order.shippingAddress && (
                <p className="text-xs text-slate-600 mt-1">
                  <strong className="text-slate-700">Delivery Address:</strong> {order.shippingAddress}
                </p>
              )}
            </div>

            <div className="border-t sm:border-t-0 sm:border-l border-slate-200 pt-3 sm:pt-0 sm:pl-4 flex flex-col justify-between">
              <div>
                <h4 className="text-[11px] font-black uppercase text-slate-400 tracking-wider mb-1.5">Payment & Order Status</h4>
                <div className="flex items-center gap-2 mb-1.5">
                  <span className={`px-2.5 py-0.5 text-xs font-black rounded-md border ${
                    isPaidInFull
                      ? 'bg-emerald-50 text-emerald-800 border-emerald-300'
                      : isPartiallyPaid
                      ? 'bg-amber-50 text-amber-800 border-amber-300'
                      : 'bg-rose-50 text-rose-800 border-rose-300'
                  }`}>
                    {order.paymentStatus.replace('_', ' ')}
                  </span>
                  <span className="px-2.5 py-0.5 text-xs font-bold rounded-md bg-slate-200 text-slate-800">
                    Status: {order.status.replace(/_/g, ' ')}
                  </span>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2 text-xs pt-2 border-t border-slate-200/80">
                <div>
                  <span className="text-slate-500 block text-[10px] uppercase font-bold">Total Paid</span>
                  <span className="font-black text-emerald-700 text-sm">₹{(order.paidAmount || 0).toLocaleString()}</span>
                </div>
                <div>
                  <span className="text-slate-500 block text-[10px] uppercase font-bold">Balance Due</span>
                  <span className={`font-black text-sm ${(order.balanceAmount || 0) > 0 ? 'text-rose-600' : 'text-slate-700'}`}>
                    ₹{(order.balanceAmount || 0).toLocaleString()}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Items Table */}
          <div className="mb-5 overflow-hidden rounded-xl border border-slate-200">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-100 text-slate-800 text-xs font-black uppercase border-b border-slate-200">
                  <th className="py-2.5 px-3">#</th>
                  <th className="py-2.5 px-3">Item & Specifications</th>
                  <th className="py-2.5 px-3 text-center">Qty</th>
                  <th className="py-2.5 px-3 text-right">Unit Price</th>
                  <th className="py-2.5 px-3 text-right">Total Amount</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 text-xs">
                {order.items.map((item, idx) => (
                  <tr key={idx} className="hover:bg-slate-50/80">
                    <td className="py-3 px-3 font-bold text-slate-400">{idx + 1}</td>
                    <td className="py-3 px-3">
                      <p className="font-black text-slate-900">{item.productName}</p>
                      {item.notes && <p className="text-slate-600 italic text-[11px] mt-0.5">{item.notes}</p>}
                    </td>
                    <td className="py-3 px-3 text-center font-bold text-slate-800">{item.quantity}</td>
                    <td className="py-3 px-3 text-right font-medium text-slate-700">₹{(item.unitPrice || 0).toLocaleString()}</td>
                    <td className="py-3 px-3 text-right font-black text-slate-900">
                      ₹{(item.totalPrice || ((item.quantity || 1) * (item.unitPrice || 0)) || 0).toLocaleString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Custom Craft Specifications (if present) */}
          {order.customDetails && (
            <div className="mb-5 p-3.5 bg-purple-50/70 rounded-xl border border-purple-200 text-xs space-y-1">
              <h5 className="font-black text-purple-950 uppercase tracking-wider flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-purple-600" />
                Custom Craft & Personalization Details
              </h5>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-1 text-slate-700 pt-1">
                {order.customDetails.designName && (
                  <p><strong className="text-slate-900">Design Name:</strong> {order.customDetails.designName}</p>
                )}
                {order.customDetails.material && (
                  <p><strong className="text-slate-900">Material/Base:</strong> {order.customDetails.material}</p>
                )}
                {order.customDetails.dimensions && (
                  <p><strong className="text-slate-900">Dimensions:</strong> {order.customDetails.dimensions}</p>
                )}
                {order.customDetails.colorTheme && (
                  <p><strong className="text-slate-900">Color Theme:</strong> {order.customDetails.colorTheme}</p>
                )}
              </div>
              {order.customDetails.textContent && (
                <p className="pt-1 text-purple-900">
                  <strong>Custom Text / Calligraphy:</strong> <span className="font-serif italic font-bold">"{order.customDetails.textContent}"</span>
                </p>
              )}
              {order.customDetails.instructions && (
                <p className="text-slate-600 text-[11px]">
                  <strong>Special Instructions:</strong> {order.customDetails.instructions}
                </p>
              )}
            </div>
          )}

          {/* Financial Calculation & Payment Settlement Summary */}
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-stretch gap-4 mb-6 pt-2">
            {/* UPI & Payment info block with Click to Display QR */}
            <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200 text-xs w-full sm:w-80 flex flex-col justify-between space-y-2">
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <p className="font-bold text-slate-800 flex items-center gap-1.5">
                    <QrCode className="w-4 h-4 text-purple-600" />
                    <span>UPI Bill Payment QR</span>
                  </p>
                  <button
                    type="button"
                    onClick={() => setShowQRModal(true)}
                    className="print:hidden text-[11px] font-bold text-purple-700 hover:text-purple-900 bg-purple-100 hover:bg-purple-200 px-2 py-0.5 rounded-md flex items-center gap-1 transition-colors cursor-pointer"
                  >
                    <Maximize2 className="w-3 h-3" />
                    <span>Enlarge QR</span>
                  </button>
                </div>

                <div className="flex items-center gap-3">
                  {/* Scannable Inline QR image (Printable & Clickable) */}
                  <div
                    onClick={() => setShowQRModal(true)}
                    className="w-24 h-24 bg-white p-1.5 rounded-lg border border-slate-300 shadow-2xs shrink-0 cursor-pointer hover:border-purple-500 transition-all group relative flex items-center justify-center"
                    title="Click to display full QR Code"
                  >
                    {qrCodeDataUrl ? (
                      <img
                        src={qrCodeDataUrl}
                        alt="UPI QR Code"
                        className="w-full h-full object-contain"
                      />
                    ) : (
                      <div className="w-5 h-5 border-2 border-purple-600 border-t-transparent rounded-full animate-spin" />
                    )}
                    <div className="absolute inset-0 bg-purple-900/10 opacity-0 group-hover:opacity-100 rounded-lg transition-opacity flex items-center justify-center print:hidden">
                      <span className="bg-purple-900 text-white text-[9px] font-bold px-1.5 py-0.5 rounded">Scan</span>
                    </div>
                  </div>

                  <div className="space-y-1 min-w-0">
                    <p className="text-[11px] text-slate-500">
                      Scan to pay total bill <strong className="text-slate-900">₹{(order.grandTotal || 0).toLocaleString()}</strong>
                    </p>
                    {upiId && (
                      <p className="text-slate-600 text-[10px] break-all font-mono font-bold bg-white px-1.5 py-0.5 rounded border border-slate-200">
                        {upiId}
                      </p>
                    )}
                    <button
                      type="button"
                      onClick={() => setShowQRModal(true)}
                      className="print:hidden w-full text-left font-black text-purple-700 hover:underline text-[11px] flex items-center gap-1 pt-0.5 cursor-pointer"
                    >
                      <span>Click to display QR</span>
                      <ExternalLink className="w-3 h-3" />
                    </button>
                  </div>
                </div>
              </div>

              <div>
                {(order.balanceAmount || 0) > 0 ? (
                  <p className="text-amber-800 font-semibold text-[11px] bg-amber-50 p-2 rounded-lg border border-amber-200">
                    Balance Due: <strong>₹{(order.balanceAmount || 0).toLocaleString()}</strong> payable via UPI scan.
                  </p>
                ) : (
                  <p className="text-emerald-800 font-bold text-[11px] bg-emerald-50 p-2 rounded-lg border border-emerald-200 flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>Receipt Settled in Full</span>
                  </p>
                )}
              </div>
            </div>

            {/* Calculations Breakdown */}
            <div className="w-full sm:w-72 space-y-1.5 text-xs bg-slate-50 sm:bg-transparent p-3 sm:p-0 rounded-xl border sm:border-0 border-slate-200">
              <div className="flex justify-between text-slate-600">
                <span>Subtotal Amount:</span>
                <span className="font-bold text-slate-800">₹{(order.subtotal || order.grandTotal || 0).toLocaleString()}</span>
              </div>
              {(order.discount || 0) > 0 && (
                <div className="flex justify-between text-emerald-700">
                  <span>Promotional Discount:</span>
                  <span className="font-bold">- ₹{(order.discount || 0).toLocaleString()}</span>
                </div>
              )}
              {(order.deliveryCharge || 0) > 0 && (
                <div className="flex justify-between text-slate-600">
                  <span>Shipping & Delivery:</span>
                  <span className="font-bold text-slate-800">+ ₹{(order.deliveryCharge || 0).toLocaleString()}</span>
                </div>
              )}
              {(order.tax || 0) > 0 && (
                <div className="flex justify-between text-slate-600">
                  <span>Estimated Tax (GST):</span>
                  <span className="font-bold text-slate-800">+ ₹{(order.tax || 0).toLocaleString()}</span>
                </div>
              )}
              <div className="flex justify-between text-sm sm:text-base font-black text-slate-900 pt-2 border-t-2 border-slate-900">
                <span>Grand Total:</span>
                <span>₹{(order.grandTotal || 0).toLocaleString()}</span>
              </div>
              <div className="flex justify-between text-emerald-700 font-bold">
                <span>Total Paid:</span>
                <span>₹{(order.paidAmount || 0).toLocaleString()}</span>
              </div>
              <div className="flex justify-between font-black text-sm pt-1.5 border-t border-dashed border-slate-300">
                <span className={(order.balanceAmount || 0) > 0 ? 'text-rose-700' : 'text-slate-800'}>
                  Balance Due:
                </span>
                <span className={(order.balanceAmount || 0) > 0 ? 'text-rose-700' : 'text-emerald-700'}>
                  ₹{(order.balanceAmount || 0).toLocaleString()}
                </span>
              </div>
            </div>
          </div>

          {/* Footer Terms & Acknowledgement */}
          <div className="border-t border-slate-300 pt-4 text-center text-slate-500 text-[11px] space-y-1">
            <p className="font-bold text-slate-800 text-xs">Thank you for your business with {bizName}!</p>
            <p>Every craft piece is uniquely handcrafted with care. For any questions regarding your order, contact us on WhatsApp at {bizPhone}.</p>
            <p className="text-[10px] text-slate-400 font-mono">Receipt generated on {new Date().toLocaleString('en-IN')}</p>
          </div>
        </div>
      </div>

      {/* Full-Screen / Modal QR Code Viewer */}
      {showQRModal && (
        <BillQRCodeModal
          isOpen={showQRModal}
          onClose={() => setShowQRModal(false)}
          order={order}
          settings={settings}
          title={`Bill Payment QR - Order #${order.orderNumber}`}
        />
      )}

      {/* Google Drive Hub Modal */}
      {showDriveModal && (
        <GoogleDriveHubModal
          isOpen={showDriveModal}
          onClose={() => setShowDriveModal(false)}
        />
      )}
    </div>
  );
};
